# Generated by Django 3.2.10 on 2022-01-03 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0002_hq_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_NID',
            fields=[
                ('NID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Fathername', models.CharField(max_length=100)),
                ('Education', models.CharField(max_length=50)),
                ('Soldiership', models.CharField(max_length=20)),
                ('BirthDate', models.DateTimeField()),
                ('JoinDate', models.DateTimeField(auto_now=True)),
                ('Address', models.TextField(max_length=500)),
                ('MaritalStatus', models.CharField(max_length=50)),
                ('HeadquartersID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarters.headquarters')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_SID',
            fields=[
                ('SID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NationalID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.staff_nid')),
            ],
        ),
        migrations.CreateModel(
            name='Administrative_staff',
            fields=[
                ('StaffID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.staff_sid')),
                ('Room', models.IntegerField()),
                ('Post', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technician_staff',
            fields=[
                ('StaffID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.staff_sid')),
                ('Expertise', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_tel',
            fields=[
                ('Telephone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff_sid')),
            ],
        ),
    ]
