# Generated by Django 3.2.10 on 2022-01-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_nid',
            name='Address',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='staff_nid',
            name='BirthDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff_nid',
            name='Education',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff_nid',
            name='Fathername',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_nid',
            name='MaritalStatus',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff_nid',
            name='Soldiership',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
