# Generated by Django 3.2.10 on 2022-01-05 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
        ('users', '0003_alter_staff_nid_headquartersid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_nid',
            name='HeadquartersID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarters.headquarters'),
        ),
    ]
