# Generated by Django 3.2.10 on 2022-01-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_ownership_nationalid'),
        ('users', '0004_alter_staff_nid_headquartersid'),
    ]

    operations = [
    ]
