# Generated by Django 3.2.10 on 2022-01-04 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('violations', '0001_initial'),
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMSID', models.IntegerField(unique=True)),
                ('Text', models.CharField(max_length=500)),
                ('SendTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sms1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SmsID', models.IntegerField(unique=True)),
                ('CameraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('FineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.fine1')),
                ('ViolationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.violation')),
            ],
            options={
                'unique_together': {('SmsID', 'FineID', 'CameraID', 'ViolationID')},
            },
        ),
    ]
