# Generated by Django 3.2.10 on 2022-01-18 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('violations', '0001_initial'),
        ('cameras', '0001_initial'),
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.IntegerField(unique=True)),
                ('AccNum', models.CharField(max_length=18)),
                ('PayNum', models.CharField(max_length=18)),
                ('Branch', models.IntegerField()),
                ('PaymentDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptID', models.IntegerField(unique=True)),
                ('CameraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('FineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.fine1')),
                ('ViolationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.violation')),
            ],
            options={
                'unique_together': {('ReceiptID', 'FineID', 'CameraID', 'ViolationID')},
            },
        ),
    ]
