# Generated by Django 3.2.10 on 2022-01-18 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.IntegerField(unique=True)),
                ('ServiceDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('InspectionStatus', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=500)),
                ('TotalCost', models.CharField(max_length=10)),
                ('NextSecDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.IntegerField()),
                ('CameraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff_sid')),
            ],
            options={
                'unique_together': {('MID', 'StaffID', 'CameraID')},
            },
        ),
    ]
