# Generated by Django 3.2.10 on 2022-01-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_ownership_nationalid'),
        ('maintenances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance1',
            name='StaffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff_sid'),
        ),
    ]
