# Generated by Django 3.2.10 on 2022-01-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HqID', models.IntegerField(default=0, unique=True)),
                ('Name', models.CharField(blank=True, default='No Name', max_length=100)),
                ('Address', models.CharField(blank=True, default='No Address', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hq_tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telephone', models.CharField(default='02100000000', max_length=11, unique=True)),
                ('HeadquartersID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarters.headquarters')),
            ],
        ),
    ]
