# Generated by Django 3.2.10 on 2022-01-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hq_tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telephone', models.CharField(default='02100000000', max_length=11, unique=True)),
                ('HeadquartersID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarters.headquarters')),
            ],
        ),
    ]
