# Generated by Django 3.2.10 on 2022-01-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='Description',
            field=models.CharField(default='No Description', max_length=500),
        ),
        migrations.AddField(
            model_name='violation',
            name='NegativePoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='violation',
            name='VID',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
